const pw = require('playwright')
const fs = require('fs')
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const [port, loc, w, h, x, y, cw, ch, out] = process.argv.slice(2)
;(async () => {
  const b = await pw.webkit.launch()
  const p = await (await b.newContext({ viewport: { width: +w, height: +h }, deviceScaleFactor: 2 })).newPage()
  await p.goto(`http://127.0.0.1:${port}/${loc}/`, { waitUntil: 'networkidle', timeout: 60000 })
  await p.waitForFunction(() => window.__lab?.A.mode === 'index', null, { timeout: 40000 }).catch(() => {})
  await sleep(3200)
  fs.writeFileSync(out, await p.screenshot({ clip: { x: +x, y: +y, width: +cw, height: +ch } }))
  console.log('ok ' + out)
  await b.close()
})()
