const pw = require('playwright')
const fs = require('fs')
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const [port, k = '1', W = '390', H = '844', loc = 'tr', tag = 'now'] = process.argv.slice(2)
fs.mkdirSync(`out/frames-${tag}`, { recursive: true })
;(async () => {
  const b = await pw.webkit.launch()
  const p = await (await b.newContext({ viewport: { width: +W, height: +H }, isMobile: +W < 700, hasTouch: +W < 700, deviceScaleFactor: 2 })).newPage()
  await p.goto(`http://127.0.0.1:${port}/${loc}`, { waitUntil: 'networkidle', timeout: 60000 })
  await p.waitForFunction(() => window.__lab?.A.mode === 'index', null, { timeout: 40000 }).catch(() => {})
  await sleep(3000)
  await p.evaluate(() => document.querySelector('#ui [data-go="work"]')?.click()); await sleep(4000)
  await p.evaluate((i) => document.querySelector(`#ui [data-work="${i}"]`)?.click(), +k)
  await p.waitForFunction((i) => window.__lab.A.wLocked === i, +k, { timeout: 20000 }).catch(() => {})
  await sleep(900)
  await p.evaluate((i) => document.querySelector(`#ui [data-work="${i}"]`)?.click(), +k)
  await p.waitForFunction(() => window.__lab.A.mode === 'world' && !window.__lab.A.busy, null, { timeout: 25000 }).catch(() => {})
  await sleep(2600)
  const n = await p.evaluate((i) => window.__lab.frames(i).length, +k)
  for (let i = 0; i < n; i++) {
    await p.evaluate((j) => { const A = window.__lab.A; A.wbase = j; A.wpT = j; A.gesture = false; A.lastInput = -1e9 }, i)
    await sleep(2600)
    const g = await p.evaluate((j) => window.__lab.frames(window.__lab.A.k)[j]?.g, i)
    fs.writeFileSync(`out/frames-${tag}/${loc}-k${k}-f${i}-${g}.png`, await p.screenshot())
    console.log(`frame ${i} g=${g}`)
  }
  await b.close()
})()
